<a href="https://colab.research.google.com/github/SandovalErick19/Python-Testing/blob/master/FirstAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
jovian.commit(project='assignment1')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/emscanalyst/assignment1


'https://jovian.ai/emscanalyst/assignment1'

In [10]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1ByPBOQepulWrSjABP3Xa7UbayJn9-JbP')

     |████████████████████████████████| 71kB 4.6MB/s 


In [6]:
import torch

In [1]:
import numpy as np

In [4]:
data = np.random.randn(3,3)

In [5]:
data

array([[ 0.85647788,  0.04692949,  0.51994941],
       [ 0.64982697, -0.1056581 , -1.07815878],
       [-0.40891649,  0.50916157, -1.27526024]])

In [7]:
convertion = torch.from_numpy(data)

In [8]:
convertion

tensor([[ 0.8565,  0.0469,  0.5199],
        [ 0.6498, -0.1057, -1.0782],
        [-0.4089,  0.5092, -1.2753]], dtype=torch.float64)

In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])